Task 7 Concurrency
MrKAKTyC/lets-go-chat pull request #7
Opened 2021-12-22 15:16 UTC by MrKAKTyC

2022-01-12 14:08 UTC, AndrianaY requested changes

2022-01-12 14:08 UTC, AndrianaY commented on pkg/repository/dbConnector.go
> +	if db == nil {
handle error please

2022-01-12 14:08 UTC, AndrianaY commented on pkg/service/otp_test.go
> +var DBuserID = "UUID-ID"
make it local please

2022-01-13 15:05 UTC, MrKAKTyC commented on pkg/repository/dbConnector.go
> +	if db == nil {
This is not an error. It's a kind of singleton implementation. If no instance of DB then create one, else return existing.

2022-01-28 14:31 UTC, merged